name: Build gh-pages
on:
  push:
    branches: [ main ]
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf *
          git add .
          git commit --allow-empty -m "Build Reset"
          git push
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: | 
          npm run build
          cd build
      - name: Commit files
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          commit_message: Build 
          push_options: '--force'