name: Build gh-pages
on:
  push:
    branches: [ main ]
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest      
    steps:
      - name: clean the gh-pages
      - uses: actions/checkout@v2
        with: 
          ref: gh-pages
      - run: |
        git clean  -d  -f .
      - name: Create build from main branch
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - name: Commit files
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*
          branch: gh-pages
          commit_message: build project for github pages
          push_options: '--force'